### ISSUE TITLE
Remove application layer logic from UserAuth::challenge()

### ISSUE THREAD

**Issue by olegbaturin** [yiisoft/user#101]
Метод [UserAuth::challenge()](https://github.com/yiisoft/user/blob/896366d4c64fe65ee25d86d69957a9555cb92dc2/src/UserAuth.php#L39) должен возвращать переданный в него $response. Приложение должно само подготовить Response в соответствии с его логикой обработки неаутентифицированного пользователя в обрабтчике RequestHandlerInterface который конфигурируется в мидваре Authentication пакета yiisoft/auth через свойство [failureHandler](https://github.com/yiisoft/auth/blob/3dd4aef867509ed686f94de3ca9038e6ac978c74/src/Middleware/Authentication.php#L26).

Логика с 302 редиректом подходит для обычного приложения с рендерингом ответа на бэкэнде, но не подходит для SPA приложения.

Пример обработчика ответа
```
final class AuthRequestErrorHandler implements RequestHandlerInterface
{
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        return $this->responseFactory
            ->createResponse(Status::FOUND)
            ->withHeader('Location', $this->authUrl);
    }
}
```

di
```
Authentication::class => [
    'class' => Authentication::class,
    '__construct()' => [
        'authenticationFailureHandler' => Reference::to(AuthRequestErrorHandler::class),
    ],
],
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 2.2.0

**Comment by vjik** [comment]
There are two way to make same thing:

1) Add own failure handler to `Authentication` middleware.

2) Add code to `AuthenticationMethodInterface::challenge()`.

May be remove `AuthenticationMethodInterface::challenge()`?
