### ISSUE TITLE
AutoLoginMiddleware and pluralism of user sessions

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/user#11]
I think that the logic of the automatic authorization mechanism is broken in AutoLoginMiddleware, since it does not take into account the pluralism of user tokens and user sessions.

1. https://github.com/yiisoft/user/blob/7d57a7f453281e01dac7ca0c15f3b23f82a10d26/src/AutoLoginMiddleware.php#L81
The search is performed by ID and not by token (or better token + id). Also the type of token should be considered.
2. The [AutoLoginIdentityInterface](https://github.com/yiisoft/user/blob/7d57a7f453281e01dac7ca0c15f3b23f82a10d26/src/AutoLoginIdentityInterface.php) extends IdentityInterface instead of declaring the methods of a separate service.

A user can have multiple sessions on different devices.
Using one key for all cases is not a good idea.

I suggest:

1. First, detach the token from user #3
2. Use `IdentityRepositoryInterface with the token` from #3 to search for Identity by token and service type in `AutoLoginMiddleware`, or create a new interface that will also accept `identity.id` in the search method signature.
3. Transfer `AutoLoginIdentityInterface` methods to a service.

Or, adopt another mechanism for extending the session like a refresh token.

**Comment by armpogart** [comment]
See also #22

**Comment by samdark** [comment]
https://github.com/yiisoft/user/issues/26
