### ISSUE TITLE
Rename User to UserService

### ISSUE THREAD

**Issue by vjik** [yiisoft/user#19]
In many applications has class `User` as domain object. `User` in this package is service. May rename him to `UserService`?

**Comment by samdark** [comment]
Yes. Good idea.

**Comment by armpogart** [comment]
Maybe it will be better to rename it to `IdentityService`?

**Comment by samdark** [comment]
@armpogart likely that won't reflect the purpose of the class well.

**Comment by terabytesoftw** [comment]
User and UserService are commonly used in any application, the purpose of the class is to have the identity of the user, from this point of view it seems good that it is called IdentityService, and so there will be no collisions in the names.

**Comment by rustamwin** [comment]
`AuthService`?

**Comment by vjik** [comment]
`CurrentUser` ?

**Comment by armpogart** [comment]
`UserService` - often applications has their `UserService`, so we will again have a collision, if we are going to rename it to `UserService`, we can also keep it just `User` which is not good at first place.
`AuthService` - will not be appropriate name as this class doesn't do any authentication per se, authentication is done in middlewares using `UserAuth` method for example.
`CurrentUser` - this name is ok, but it has a one problem. This class doesn't reflect our user, which is usually our entity.

Everything in this class is written to help to work with the `IdentityInterface` through `IdentityRepository`, so I think that the name that really reflects the purpose of the class is `IdentityService` as the class has `getIdentity()`, `switchIdentity()`, `renewIdentity()`, and access checking for current `IdentityInterface`. So it's just a service to work with identity.

**Comment by Nex-Otaku** [comment]
The class does two things:
1. Authenticates user (login, logout, etc)
2. Checks user access to restricted areas

So, it should be divided to two classes:
1. Authentication
2. AccessChecker

The are two packages desgined for this, "auth" and "access", so Authentication can be moved to "auth" package, and AccessChecker can be moved to "access" package.

**Comment by Nex-Otaku** [comment]
No "Services" and "Managers" should be anywhere in the framework, as those names are too abstract and are not describing anything at all.

**Comment by vjik** [comment]
Maybe part of package move to `yiisoft/auth` (create interface for `AutoLoign`, `GuestIdentity`, `User`, etc.). This package rename to `yii-identity` or `yii-auth`. This will make the `auth` package more functional without essential increasing of dependencies. This package will be provide implementation of `auth` based on yii packages `session` and `cookie`.

**Comment by samdark** [comment]
> So, it should be divided to two classes:

https://github.com/yiisoft/access/blob/master/src/AccessCheckerInterface.php whose implementation is RBAC. This packages has it for convenience. The method for access checking is where the data is so data isn't passed as an argument all the time.
