### ISSUE TITLE
User identity stuck in RoadRunner environment

### ISSUE THREAD

**Issue by samdark** [yiisoft/user#2]
Currently Identity instance is stored as state in https://github.com/yiisoft/yii-web/blob/master/src/User/User.php#L33 and it's not being cleaned up so it stucks in RoadRunner environment.

**Comment by vjik** [comment]
@samdark Does [this code](https://github.com/yiisoft/user/blob/master/config/web.php#L14-L19) solve the problem?

**Comment by samdark** [comment]
Yes.
