### ISSUE TITLE
Make User and AutoLoginMiddleware more universal

### ISSUE THREAD

**Issue by armpogart** [yiisoft/user#22]
Both `User` and `AutoLoginMiddleware` currently work only for session/cookie base authentication/authorization.
I propose to make the more abstract using concrete implementation under the hood which will allow user authentication/authorization in different scenarios (for example for token based authentication/authorization for API requests where session/cookies are not used).

**Comment by samdark** [comment]
1. AutoLoginMiddleware doesn't make sense for tokens. A long-living token is the same as what's set/read by the middleware.
2. Being able to use User w/o session is good.

**Comment by samdark** [comment]
Maybe it makes sense to have TokenLoginMiddleware.
