### ISSUE TITLE
Need method to set cookie durantion in runtime

### ISSUE THREAD

**Issue by g-rodigy** [yiisoft/user#85]
CookieLogin need method `withDuration` for set cookie with this duration. By default cookie duration set in config and no way to change it. For example cookie duration is null (session cookie) and need set to some long time from form like "Remember Me" option.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 2.0.0

**Comment by vjik** [comment]
This can be resolved by two ways:
1) Create new method `addCookieWithDuartion`
2) Add parameter `$duration` to existing method `addCookie`

**Comment by samdark** [comment]
2nd way makes sense.

**Comment by vjik** [comment]
Done by #86
